jwt:
  secret: F5C82B1AB2CH3E4F2F7V787E5AA1M21BC2DW2KE9NB3U9K1L15JB8EB4Q9
  expirationMs: 3600000
  refreshExpirationMs: 86400000
  
spring:
  application:
    name: team-project

  datasource:
    url: jdbc:mysql://localhost:3306/team
    username: root
    password: "0304"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  mail:
    host: smtp.gmail.com        # SMTP 서버 호스트
    port: 587                   # SMTP 서버 포트
    username: beomjin754        # SMTP 서버 로그인 아이디
    password: rydcftyyuvpthhfs  # SMTP 서버 로그인 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부