name: Production Deploy

on:
  push:
    branches:
      - 'production'

env:
  APP_ENV: production
  AWS_REGION: ap-northeast-2
  ECR_REPO: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team06-be-production-repo
  INFRA_REPO: https://github.com/TP1-OuterMSA/msa-infra-main.git
  SERVICE_PATH: charts/services/team06-be
  

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build and Push Docker Image
        run: |
          docker build -t team06-be .
          docker tag team06-be:latest ${{ env.ECR_REPO }}:sha-${SHORT_SHA}
          docker push ${{ env.ECR_REPO }}:sha-${SHORT_SHA}

      - name: Clone Infra Repo and Update Helm Tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${GH_PAT}@github.com/TP1-OuterMSA/msa-infra-main.git
          cd msa-infra-main/charts/services/team06-be

          # SHA로 이미지 태그 변경
          sed -i "s/tag: \".*\"/tag: \"sha-${SHORT_SHA}\"/" values.yaml

          # Git 설정 및 push
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add values.yaml
          git commit -m "chore(team06-be): update image tag to sha-${SHORT_SHA}"
          git push https://${GH_PAT}@github.com/TP1-OuterMSA/msa-infra-main.git HEAD:main
